/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */


import { ethers } from 'ethers'
import { DeployContractOptions, FactoryOptions, HardhatEthersHelpers as HardhatEthersHelpersBase} from "@nomicfoundation/hardhat-ethers/types";

import * as Contracts from "./index.js";

declare module "@nomicfoundation/hardhat-ethers/types" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
  getContractFactory(name: 'BaseStrategy', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.BaseStrategy__factory>
getContractFactory(name: 'Counter', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.Counter__factory>
getContractFactory(name: 'IStrategy', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IStrategy__factory>
getContractFactory(name: 'LPStrategy', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.LPStrategy__factory>
getContractFactory(name: 'LendingStrategy', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.LendingStrategy__factory>
getContractFactory(name: 'StakingStrategy', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.StakingStrategy__factory>
getContractFactory(name: 'Vault', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.Vault__factory>

  getContractAt(name: 'BaseStrategy', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.BaseStrategy>
getContractAt(name: 'Counter', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.Counter>
getContractAt(name: 'IStrategy', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IStrategy>
getContractAt(name: 'LPStrategy', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.LPStrategy>
getContractAt(name: 'LendingStrategy', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.LendingStrategy>
getContractAt(name: 'StakingStrategy', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.StakingStrategy>
getContractAt(name: 'Vault', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.Vault>

  deployContract(name: 'BaseStrategy', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.BaseStrategy>
deployContract(name: 'Counter', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.Counter>
deployContract(name: 'IStrategy', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IStrategy>
deployContract(name: 'LPStrategy', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.LPStrategy>
deployContract(name: 'LendingStrategy', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.LendingStrategy>
deployContract(name: 'StakingStrategy', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.StakingStrategy>
deployContract(name: 'Vault', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.Vault>

  deployContract(name: 'BaseStrategy', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.BaseStrategy>
deployContract(name: 'Counter', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.Counter>
deployContract(name: 'IStrategy', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IStrategy>
deployContract(name: 'LPStrategy', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.LPStrategy>
deployContract(name: 'LendingStrategy', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.LendingStrategy>
deployContract(name: 'StakingStrategy', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.StakingStrategy>
deployContract(name: 'Vault', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.Vault>

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
  }
}
  