/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface VaultInterface extends Interface {
    getFunction(nameOrSignature: "addStrategy" | "deposit" | "owner" | "rebalance" | "setWeights" | "shares" | "strategies" | "strategyCount" | "totalShares" | "totalValue" | "userValue" | "withdraw"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "Deposit" | "Rebalance" | "Withdraw"): EventFragment;

    encodeFunctionData(functionFragment: 'addStrategy', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'deposit', values?: undefined): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'rebalance', values?: undefined): string;
encodeFunctionData(functionFragment: 'setWeights', values: [BigNumberish[]]): string;
encodeFunctionData(functionFragment: 'shares', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'strategies', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'strategyCount', values?: undefined): string;
encodeFunctionData(functionFragment: 'totalShares', values?: undefined): string;
encodeFunctionData(functionFragment: 'totalValue', values?: undefined): string;
encodeFunctionData(functionFragment: 'userValue', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'withdraw', values?: undefined): string;

    decodeFunctionResult(functionFragment: 'addStrategy', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'deposit', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'rebalance', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setWeights', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'shares', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'strategies', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'strategyCount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'totalShares', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'totalValue', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'userValue', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'withdraw', data: BytesLike): Result;
  }

  
    export namespace DepositEvent {
      export type InputTuple = [user: AddressLike, amount: BigNumberish, sharesMinted: BigNumberish];
      export type OutputTuple = [user: string, amount: bigint, sharesMinted: bigint];
      export interface OutputObject {user: string, amount: bigint, sharesMinted: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RebalanceEvent {
      export type InputTuple = [timestamp: BigNumberish];
      export type OutputTuple = [timestamp: bigint];
      export interface OutputObject {timestamp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace WithdrawEvent {
      export type InputTuple = [user: AddressLike, amount: BigNumberish, sharesBurned: BigNumberish];
      export type OutputTuple = [user: string, amount: bigint, sharesBurned: bigint];
      export interface OutputObject {user: string, amount: bigint, sharesBurned: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface Vault extends BaseContract {
    
    connect(runner?: ContractRunner | null): Vault;
    waitForDeployment(): Promise<this>;

    interface: VaultInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    addStrategy: TypedContractMethod<
      [_strategy: AddressLike, _weight: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    deposit: TypedContractMethod<
      [],
      [void],
      'payable'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    rebalance: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    setWeights: TypedContractMethod<
      [_weights: BigNumberish[], ],
      [void],
      'nonpayable'
    >
    

    
    shares: TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    strategies: TypedContractMethod<
      [arg0: BigNumberish, ],
      [[string, bigint] & {strategy: string, weight: bigint }],
      'view'
    >
    

    
    strategyCount: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    totalShares: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    totalValue: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    userValue: TypedContractMethod<
      [_user: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    withdraw: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'addStrategy'): TypedContractMethod<
      [_strategy: AddressLike, _weight: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'deposit'): TypedContractMethod<
      [],
      [void],
      'payable'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'rebalance'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setWeights'): TypedContractMethod<
      [_weights: BigNumberish[], ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'shares'): TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'strategies'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [[string, bigint] & {strategy: string, weight: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'strategyCount'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'totalShares'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'totalValue'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'userValue'): TypedContractMethod<
      [_user: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'withdraw'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'Deposit'): TypedContractEvent<DepositEvent.InputTuple, DepositEvent.OutputTuple, DepositEvent.OutputObject>;
getEvent(key: 'Rebalance'): TypedContractEvent<RebalanceEvent.InputTuple, RebalanceEvent.OutputTuple, RebalanceEvent.OutputObject>;
getEvent(key: 'Withdraw'): TypedContractEvent<WithdrawEvent.InputTuple, WithdrawEvent.OutputTuple, WithdrawEvent.OutputObject>;

    filters: {
      
      'Deposit(address,uint256,uint256)': TypedContractEvent<DepositEvent.InputTuple, DepositEvent.OutputTuple, DepositEvent.OutputObject>;
      Deposit: TypedContractEvent<DepositEvent.InputTuple, DepositEvent.OutputTuple, DepositEvent.OutputObject>;
    

      'Rebalance(uint256)': TypedContractEvent<RebalanceEvent.InputTuple, RebalanceEvent.OutputTuple, RebalanceEvent.OutputObject>;
      Rebalance: TypedContractEvent<RebalanceEvent.InputTuple, RebalanceEvent.OutputTuple, RebalanceEvent.OutputObject>;
    

      'Withdraw(address,uint256,uint256)': TypedContractEvent<WithdrawEvent.InputTuple, WithdrawEvent.OutputTuple, WithdrawEvent.OutputObject>;
      Withdraw: TypedContractEvent<WithdrawEvent.InputTuple, WithdrawEvent.OutputTuple, WithdrawEvent.OutputObject>;
    
    };
  }